# FastAPI application — the entry point for the entire system.
# Run with: uvicorn main:app --reload --port 8000
# API docs available at: http://localhost:8000/docs (auto-generated by FastAPI)

import time  # for latency tracking
from fastapi import FastAPI, HTTPException, UploadFile  # web framework
from pydantic import BaseModel  # request/response validation

# ── Import all our modules ──
from src.ingestion.pipeline import process_local_document
from src.search.vector_store import VectorStore
from src.search.bm25_index import BM25Index
from src.search.hybrid import hybrid_search
from src.rag.generator import generate_answer
from src.agent.react_agent import run_agent
from src.upload.presigned import (
    request_upload, save_local_upload, update_document_status, get_document_status
)
from src.storage.document_store import delete_document_record
from src.guardrails.model_router import classify_intent, select_model
from src.guardrails.hallucination import check_grounding, apply_grounding_result
from src.guardrails.pii_detector import detect_pii, redact_pii

# ── Initialize FastAPI app ──
app = FastAPI(
    title="Document Processing AI Agent",
    description="RAG + AI Agent for document analysis with hybrid search",
    version="1.0.0"
)

# ── Initialize global instances ──
# These are created once at startup and shared across all requests
# In production, you'd use dependency injection, but globals are fine for learning
vector_store = VectorStore()  # ChromaDB — loads from disk if data exists
bm25_index = BM25Index()      # BM25 — starts empty, built during ingestion


def _refresh_bm25_index() -> None:
    # Keep BM25 aligned with persisted Chroma data so the API can read worker updates.
    bm25_index.build(vector_store.get_all_chunks())


# ── Request/Response Models ──
# Pydantic models validate incoming requests and document the API shape

class UploadRequest(BaseModel):
    """Request body for POST /api/documents/request-upload"""
    filename: str           # e.g., "contract.pdf"
    content_type: str       # e.g., "application/pdf"
    size_bytes: int         # file size in bytes


class QueryRequest(BaseModel):
    """Request body for POST /api/query"""
    question: str                         # the user's question
    doc_ids: list[str] = []               # optional: limit search to specific docs
    mode: str = "search"                  # "search" = basic RAG, "agent" = ReAct agent


# ── Health Check ──
@app.get("/health")
def health_check():
    """
    Simple health check endpoint.
    Returns 200 if the server is running.
    Used by load balancers and monitoring to verify the service is alive.
    """
    stats = vector_store.get_stats()
    return {
        "status": "healthy",
        "total_chunks_indexed": stats["total_chunks"]
    }


# ── Upload Endpoints ──

@app.post("/api/documents/request-upload")
def api_request_upload(req: UploadRequest):
    """
    Step 1 of upload: validate and generate a pre-signed URL.
    Client will use this URL to upload directly to S3 (or local in dev).
    """
    try:
        result = request_upload(req.filename, req.content_type, req.size_bytes)
        return result
    except ValueError as e:
        # Validation failed (wrong file type, too large)
        raise HTTPException(status_code=400, detail=str(e))


@app.post("/api/documents/{doc_id}/upload-local")
async def api_upload_local(doc_id: str, file: UploadFile):
    """
    Local development only: receive the file directly.
    In production, the client uploads to S3 via pre-signed URL instead.
    """
    # Read the file content
    content = await file.read()  # async read — doesn't block the server

    # Check if file is actually not empty
    if not content or len(content) == 0:
        raise HTTPException(status_code=400, detail=f"Uploaded file is empty (0 bytes). Filename: {file.filename}, Content-Type: {file.content_type}")

    # Save to local storage
    file_path = save_local_upload(doc_id, content, file.filename)

    # Update status
    update_document_status(doc_id, status="uploaded", filename=file.filename)

    return {
        "doc_id": doc_id,
        "file_path": file_path,
        "size_bytes": len(content),
        "status": "uploaded"
    }


@app.post("/api/documents/{doc_id}/process")
def api_process_document(doc_id: str):
    """
    Trigger document processing (ingestion pipeline).
    In production: S3 Event → SQS → Worker calls this automatically.
    For local dev: client calls this after uploading.

    Pipeline: extract text → chunk → embed → index
    """
    try:
        result = process_local_document(doc_id)
        _refresh_bm25_index()
        return result
    except FileNotFoundError as exc:
        raise HTTPException(status_code=404, detail=str(exc))
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Processing failed: {str(exc)}")


@app.get("/api/documents/{doc_id}/chunks")
def api_document_chunks(doc_id: str, page: int = None, limit: int = 20):
    """
    View chunks for a document. Useful for debugging ingestion.
    Optional: filter by page number, limit results.
    """
    results = vector_store.search("", top_k=1000, doc_id=doc_id) if doc_id else []
    # Fallback: get chunks directly from ChromaDB collection
    collection_results = vector_store._collection.get(
        where={"doc_id": doc_id},
        limit=limit
    )
    chunks = []
    for i in range(len(collection_results["ids"])):
        chunk = {
            "chunk_id": collection_results["ids"][i],
            "text": collection_results["documents"][i][:200] + "..." if len(collection_results["documents"][i]) > 200 else collection_results["documents"][i],
            "full_text_length": len(collection_results["documents"][i]),
            "page_num": collection_results["metadatas"][i]["page_num"],
            "token_count": collection_results["metadatas"][i].get("token_count", 0)
        }
        if page is None or chunk["page_num"] == page:
            chunks.append(chunk)

    chunks.sort(key=lambda x: x["page_num"])
    return {
        "doc_id": doc_id,
        "total_chunks": len(chunks),
        "chunks": chunks
    }


@app.get("/api/documents/{doc_id}/status")
def api_document_status(doc_id: str):
    """
    Check document processing status.
    Client polls this to know when processing is done.
    Returns: pending → uploaded → processing → ready (or failed)
    """
    status = get_document_status(doc_id)
    if "error" in status:
        raise HTTPException(status_code=404, detail="Document not found")
    return status


# ── Query Endpoint ──

@app.post("/api/query")
def api_query(req: QueryRequest):
    """
    Main query endpoint — handles both basic RAG and agent mode.

    Flow:
    1. Classify the query intent (simple_lookup, compare, analyze, etc.)
    2. Select the right LLM model based on intent
    3. Route to basic RAG (single search + generate) or agent (multi-step)
    4. Run hallucination check on the answer
    5. Run PII check on the answer
    6. Return the response with metadata
    """
    start_time = time.time()

    # ── Step 0: PII check on the incoming question ──
    # Block queries that contain sensitive data (SSN, credit card, etc.)
    # This prevents PII from being sent to the LLM
    input_pii = detect_pii(req.question)
    if input_pii["has_pii"]:
        pii_types = [e["type"] for e in input_pii["entities"]]
        return {
            "answer": f"⚠️ Your question contains sensitive information ({', '.join(pii_types)}). Please remove PII before querying.",
            "confidence": "none",
            "sources": [],
            "pii_detected": True,
            "pii_types": pii_types,
            "model": "none",
            "intent": "blocked"
        }

    # ── Step 1: Classify intent and select model ──
    intent = classify_intent(req.question)
    model = select_model(intent)
    _refresh_bm25_index()

    if req.mode == "agent":
        # ── Agent mode: always use COMPLEX_MODEL ──
        # Agent needs stronger reasoning to decide which tools to call
        # Model routing only applies to basic RAG (search mode)
        from src.config import COMPLEX_MODEL
        model = COMPLEX_MODEL
        result = run_agent(
            query=req.question,
            vector_store=vector_store,
            bm25_index=bm25_index,
            model=model
        )
    else:
        # ── Search mode: single-hop RAG ──
        # Step 2a: Search for relevant chunks
        chunks = hybrid_search(req.question, vector_store, bm25_index, top_k=5)

        # Step 2b: Generate answer from chunks
        result = generate_answer(req.question, chunks, model=model)
        # Store chunks for grounding check
        result["_chunks"] = chunks

    # ── Step 3: Hallucination check ──
    # Get the source texts that were used
    source_texts = []
    if "_chunks" in result:
        source_texts = [c["text"] for c in result["_chunks"]]
        del result["_chunks"]  # don't return internal data to client

    if source_texts:
        grounding = check_grounding(result["answer"], source_texts)
        result = apply_grounding_result(result, grounding)

    # ── Step 4: PII check on the answer ──
    pii_result = detect_pii(result["answer"])
    if pii_result["has_pii"]:
        # Redact PII from the answer before returning to the user
        result["answer"] = redact_pii(result["answer"], pii_result["entities"])
        result["pii_redacted"] = True

    # ── Step 5: Add metadata ──
    total_latency = int((time.time() - start_time) * 1000)
    result["intent"] = intent
    result["total_latency_ms"] = total_latency

    return result


# ── Delete Document ──

@app.delete("/api/documents/{doc_id}")
def api_delete_document(doc_id: str):
    """
    Remove a document and all its chunks from both indexes.
    """
    # Remove from vector store
    vector_store.delete_document(doc_id)
    # Remove from BM25 index
    bm25_index.delete_document(doc_id)
    # Remove persisted status metadata
    delete_document_record(doc_id)

    return {"doc_id": doc_id, "status": "deleted"}
